[package]
name = "avr-boot-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
avr-tester = "0.4.0"
test-case = "2.2.2"

[patch.crates-io]
simavr-ffi = { git = 'https://github.com/orukusaki/simavr-ffi.git', branch="update-simavr"}