name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - name: Install dependencies
      run: sudo apt install -y gcc-avr avr-libc libelf-dev pkg-config
    - uses: actions/checkout@v3
    - name: Build
      working-directory: avr-boot
      run: cargo build --verbose --release -Zbuild-std=core --target=../.cargo/targets/atmega328.json
    - name: Run tests
      working-directory: avr-boot-tests
      run: cargo test --verbose -j1
    - name: Generate docs
      working-directory: avr-boot
      run: cargo doc