name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: install dependencies
      run: sudo apt install -y gcc-avr avr-libc libelf-dev
    - uses: actions/checkout@v3
  build:
    needs: setup
    runs-on: ubuntu-latest  
    defaults:
      run:
        working-directory: ./avr-boot
    steps:
    - name: Build
      run: cargo build --verbose --release
  test:
    runs-on: ubuntu-latest  
    needs: setup
    defaults:
      run:
        working-directory: ./avr-boot-tests
    steps:
    - name: Run tests
      run: cargo test --verbose