name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt install -y build-essential make gcc-avr avr-libc libelf-dev clang pkg-config
    - uses: actions/checkout@v4
    - name: Build
      working-directory: avr-boot
      run: RUSTFLAGS='-Ctarget-cpu=atmega328p' cargo build --verbose --release -Zbuild-std=core --target=../.cargo/targets/atmega328.json
    - name: Run unit/doc tests
      working-directory: avr-boot
      run: cargo test
    # - name: Run integration tests
    #   working-directory: avr-boot-tests
    #   run: cargo test --verbose -j1
    - name: Generate docs
      working-directory: avr-boot
      run: cargo doc